version = 0.1
[default.deploy.parameters]
stack_name = "Testing-Comprehend-Lambda-Apigw"
resolve_s3 = true
s3_prefix = "Testing-Comprehend-Lambda-Apigw"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
